{% set name = "screen" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/screen/screen-{{ version }}.tar.gz
  sha256: ca9a2c7e240919bc7ac12124593ae4529bb4eb5f7349d8857829b7e3f0b3b332

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - gawk
    - make
    - perl >=5.32
  host:
    - libxcrypt
    - ncurses

test:
  commands:
    - screen -v | grep 'Screen version 5.0.2'
    - test -d ${PREFIX}/share/screen/utf8encodings

about:
  home: https://www.gnu.org/software/screen/
  summary: Terminal multiplexer with VT100/ANSI terminal emulation
  license: GPL-3.0-or-later
  license_file: COPYING
  dev_url: https://savannah.gnu.org/projects/screen/
