{% set name = "screen" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/screen/screen-{{ version }}.tar.gz
  sha256: 2dae36f4db379ffcd14b691596ba6ec18ac3a9e22bc47ac239789ab58409869d

build:
  number: 10

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libxcrypt
    - ncurses

test:
  commands:
    - screen -v | grep 'Screen version 5.0.1'
    - test -d ${PREFIX}/share/screen/utf8encodings

about:
  home: https://www.gnu.org/software/screen/
  summary: Terminal multiplexer with VT100/ANSI terminal emulation
  license: GPL-3.0-or-later
  license_file: COPYING
  dev_url: https://savannah.gnu.org/projects/screen/
